project:
  type: website
    
website:
  open-graph: true
  title: "Data Science PD newsletter"
  description: "A newsletter promoting professional development for data scientists at NHS England."
  site-url: https://harrietrs.github.io/pd_newsletter
  favicon: docs/_assets/favicon.ico
  repo-url: https://github.com/harrietrs/pd_newsletter
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: https://github.com/harrietrs/pd_newsletter/blob/main/LICENCE

  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "home"
        icon: "box-seam"
        href: index.qmd
      - text: "Updates"
        icon: "rss"
        href: updates.qmd
    right:
      - text: "Help"
        menu:
          - text: "About"
            icon: "info-circle"
            href: about.qmd
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/harrietrs/pd_newsletter/issues"
          - text: "FAQ"
            icon: "question-circle"
            href: faq.qmd
      - icon: github
        href: https://github.com/harrietrs/
        aria-label: GitHub
  sidebar:
    id: toc-side
    style: "floating"
    pinned: true
    contents:
      - text: "Homepage" 
        file: index.qmd
      - text: Newsletters
        href: newsletters.qmd 
      - text: "FAQ"
        file: faq.qmd
      - text: "About"
        file: about.qmd
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html

execute:
  freeze: auto